# experiment with triggering events: push, pull_request

name: CI all

on: [push, pull_request]

jobs:
  build-all:
    if: github.event.push || github.event.pull_request.head.repo.fork
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
